language: c
script: 
  - git submodule update --init
  - ./configure --prefix=$HOME/ircd --enable-ssl --disable-nls --enable-contrib
  - make
  - make install
compiler:
  - gcc
  - clang
  - g++
  - make
